### ISSUE TITLE
Error for operations on different devices: CPU versus CUDA

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#1082]
Issue reported by Nicolas Legendre (https://github.com/NicolasLegendre1)

For this code:
![image](https://user-images.githubusercontent.com/8267869/128795411-3d82704f-0be6-4be1-810b-cd9444dbd179.png)
![image](https://user-images.githubusercontent.com/8267869/128795420-9a7b6dc4-a861-4184-827a-b521bd49b841.png)

Nicolas gets the following error:
![image](https://user-images.githubusercontent.com/8267869/128795429-fde101d8-b017-429a-baf4-b758ca43370e.png)

And for this code:
![image](https://user-images.githubusercontent.com/8267869/128795447-c517ea00-61f5-44a3-8495-a530ae035bab.png)

He gets:
![image](https://user-images.githubusercontent.com/8267869/128795456-6912fb8c-74cd-49af-807b-3f0f908d05dc.png)

We should test geomstats on cpu + cuda devices, as there seem to be several incompatibilities.

**Comment by mvdoc** [comment]
Hi, first of all thank you so much for this package. I'm exploring riemaniann geometry for my work and this package and the learning materials are amazing.

I hit the same problem when trying to compute the frechet mean on a torch tensor on GPU. Here's a minimal reproducible example and the resulting traceback.

```python
import os
os.environ["GEOMSTATS_BACKEND"] = "pytorch"
import torch

import geomstats.backend as gs
import geomstats.geometry.spd_matrices as spd

manifold = spd.SPDMatrices(20)

# Generate some random data
data = gs.array([manifold.random_point() for _ in range(10)])
# Push to GPU
data = data.to("cuda")

# Compute frechet mean
from geomstats.learning.frechet_mean import FrechetMean
mean = FrechetMean(metric=manifold.metric)
mean.fit(data)
``` 

<details>
<summary>Full traceback</summary>

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-abb08f84a022> in <module>
     16 from geomstats.learning.frechet_mean import FrechetMean
     17 mean = FrechetMean(metric=manifold.metric)
---> 18 mean.fit(data)

src/lib/geomstats/geomstats/learning/frechet_mean.py in fit(self, X, y, weights)
    544                 epsilon=self.epsilon,
    545                 verbose=self.verbose,
--> 546                 init_point=self.init_point,
    547             )
    548         elif self.method == "adaptive":

src/lib/geomstats/geomstats/learning/frechet_mean.py in _default_gradient_descent(points, metric, weights, max_iter, point_type, epsilon, init_step_size, verbose, init_point)
    124 
    125     while iteration < max_iter:
--> 126         logs = metric.log(point=points, base_point=mean)
    127 
    128         var = gs.sum(metric.squared_norm(logs, mean) * weights) / gs.sum(weights)

src/lib/geomstats/geomstats/geometry/spd_matrices.py in log(self, point, base_point, **kwargs)
    660 
    661         if power_affine == 1:
--> 662             powers = SymmetricMatrices.powerm(base_point, [1.0 / 2, -1.0 / 2])
    663             log = self._aux_log(point, powers[0], powers[1])
    664         else:

src/lib/geomstats/geomstats/geometry/symmetric_matrices.py in powerm(cls, mat, power)
    201                 return gs.power(ev, power)
    202 
--> 203         return cls.apply_func_to_eigvals(mat, power_, check_positive=True)
    204 
    205     @staticmethod

src/lib/geomstats/geomstats/geometry/symmetric_matrices.py in apply_func_to_eigvals(mat, function, check_positive)
    237         for fun in function:
    238             eigvals_f = fun(eigvals)
--> 239             eigvals_f = algebra_utils.from_vector_to_diagonal_matrix(eigvals_f)
    240             reconstruction.append(Matrices.mul(eigvecs, eigvals_f, transp_eigvecs))
    241         return reconstruction if return_list else reconstruction[0]

src/lib/geomstats/geomstats/algebra_utils.py in from_vector_to_diagonal_matrix(vector, num_diag)
    117     identity = gs.eye(num_columns)
    118     identity = gs.cast(identity, vector.dtype)
--> 119     diagonals = gs.einsum("...i,ij->...ij", vector, identity)
    120     diagonals = gs.to_ndarray(diagonals, to_ndim=3)
    121     num_lines = diagonals.shape[0]

/src/lib/geomstats/geomstats/_backend/pytorch/__init__.py in einsum(*args, **kwargs)
    450         return result
    451 
--> 452     return torch.einsum(*args, **kwargs)
    453 
    454 

site-packages/torch/functional.py in einsum(*args)
    325         return einsum(equation, *_operands)
    326 
--> 327     return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
    328 
    329 

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
</details>

In this case the problem seems to arise from https://github.com/geomstats/geomstats/blob/baf78ca203355cae2ea9403e8180fc13deed55ea/geomstats/algebra_utils.py#L118 where the identity matrix is created without following the device where `vector` is stored.

**Comment by dherrera1911** [comment]
I am trying to run a model where I use a loss computed as a distance in the SPD manifold using `geomstats`, with the `pytorch` backend. The model works fine in the cpu, but not in the GPU, because of the issue mentioned here.

I tried the following opening lines to my script, to have `geomstats` instantiate the tensors in the GPU:

```
import sys
import os
import torch
if torch.cuda.is_available():
    DEVICE = 'cuda'
    torch.set_default_tensor_type(torch.cuda.DoubleTensor)
else:
    DEVICE = 'cpu'
    torch.set_default_tensor_type(torch.DoubleTensor)
os.environ['GEOMSTATS_BACKEND'] = 'pytorch'
from my_script import geometric_loss_function
```

When trying to run in the GPU I get the following error:

```
INFO: Using pytorch backend
Traceback (most recent call last):
  File "/mycluster/home/dherrera/spectral_ideal_observer/./geometry_fit.py", line 41, in <module>
    loss = training_loop_pairs(model=model,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mycluster/home/dherrera/spectral_ideal_observer/response_statistics_class.py", line 137, in training_loop_pairs
    loss = training_loop_seeds(model=model,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mycluster/home/dherrera/spectral_ideal_observer/response_statistics_class.py", line 119, in training_loop_seeds
    loss = training_loop_cycle(model=model,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mycluster/home/dherrera/spectral_ideal_observer/response_statistics_class.py", line 106, in training_loop_cycle
    loss = training_loop(model=model,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mycluster/home/dherrera/spectral_ideal_observer/response_statistics_class.py", line 92, in training_loop
    loss = loss_fun(model)
           ^^^^^^^^^^^^^^^
  File "/mycluster/home/dherrera/spectral_ideal_observer/functions_geometry.py", line 126, in loss_fun
    dist_dict = distance_matrix(covariances.view(n_covs, c, d), metric = [metric])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mycluster/home/dherrera/spectral_ideal_observer/functions_geometry.py", line 97, in distance_matrix
    distances = manifold.metric.dist(point_a = cov_expanded,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mycluster/home/dherrera/packages/miniconda3/envs/my-torch/lib/python3.11/site-packages/geomstats/geometry/riemannian_metric.py", line 370, in dist
    sq_dist = self.squared_dist(point_a, point_b, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mycluster/home/dherrera/packages/miniconda3/envs/my-torch/lib/python3.11/site-packages/geomstats/geometry/riemannian_metric.py", line 348, in squared_dist
    log = self.log(point=point_b, base_point=point_a, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mycluster/home/dherrera/packages/miniconda3/envs/my-torch/lib/python3.11/site-packages/geomstats/geometry/spd_matrices.py", line 649, in log
    powers = SymmetricMatrices.powerm(base_point, [1.0 / 2, -1.0 / 2])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mycluster/home/dherrera/packages/miniconda3/envs/my-torch/lib/python3.11/site-packages/geomstats/geometry/symmetric_matrices.py", line 202, in powerm
    return cls.apply_func_to_eigvals(mat, power_, check_positive=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mycluster/home/dherrera/packages/miniconda3/envs/my-torch/lib/python3.11/site-packages/geomstats/geometry/symmetric_matrices.py", line 242, in apply_func_to_eigvals
    eigvals_f = algebra_utils.from_vector_to_diagonal_matrix(eigvals_f)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mycluster/home/dherrera/packages/miniconda3/envs/my-torch/lib/python3.11/site-packages/geomstats/algebra_utils.py", line 119, in from_vector_to_diagonal_matrix
    diagonals = gs.einsum("...i,ij->...ij", vector, identity)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mycluster/home/dherrera/packages/miniconda3/envs/my-torch/lib/python3.11/site-packages/geomstats/_backend/pytorch/__init__.py", line 333, in einsum
    return _torch.einsum(equation, *input_tensors_list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mycluster/home/dherrera/packages/miniconda3/envs/my-torch/lib/python3.11/site-packages/torch/functional.py", line 378, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
