### ISSUE TITLE
example of gradient_descent_s2 does not work

### ISSUE THREAD

**Issue by maurinlenglart** [geomstats/geomstats#139]
The first exemple keep failing : 
```
python3 ./examples/gradient_descent_s2.py
Using numpy backend
x: [0.86604857 0.49993232 0.00524429]
reached precision 1e-05
iterations: 85
Traceback (most recent call last):
  File "./examples/gradient_descent_s2.py", line 124, in <module>
    main()
  File "./examples/gradient_descent_s2.py", line 120, in main
    np.testing.assert_almost_equal(loss(x), np.min(eig), decimal=2)
  File "/usr/local/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 584, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 2 decimals
 ACTUAL: 0.7828534176680455
 DESIRED: 0.08684823961199317

```

pip : 
```
autograd (1.2)
codecov (2.0.15)
coverage (4.5.1)
matplotlib (2.2.3)
nose2 (0.8.0)
numpy (1.15.1)
scipy (1.1.0)
tensorflow (1.10.1)
torch (0.4.0)
```

**Comment by johmathe** [comment]
Thanks for the bug report. Will have a look soon.

**Comment by johmathe** [comment]
All set Maurin - keep us posted :)
