### ISSUE TITLE
Backend Fix: function pointwise_inner_products of SRVMetric does not support broadcasting in tf

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#1575]
### Where should the content be modified?

https://github.com/geomstats/geomstats/blob/6f260f767fc06e2752a4a801557147004049943b/geomstats/geometry/discrete_curves.py#L224

### What should be modified?

The function `pointwise_inner_products` computes the inner-products of two "tangent vectors" at one base curve, where the tangent vectors are a sequence of vectors along the sampling points of the base curve.

However, this function does not work when:
- several tangent vectors (i.e. several sets of sequences of vectors along the sampling points) are provided
in the backend: `tensorflow`.

This probably comes from the fact that the function `gs.vectorize` used there behaves differently for the tensorflow backend.

### Additional information

Code sample

```
import geomstats.backend as gs
from geomstats.geometry.discrete_curves import DiscreteCurves, R2

dim = 2
n_samples = 10
n_sampling_points = 8
shape_curves_2d = (n_sampling_points, dim)
curves_2d = DiscreteCurves(R2)
metric_curves_2d = curves_2d.square_root_velocity_metric
metric_curves_2d.default_point_type = "matrix"

base_curve = curves_2d.random_point(n_sampling_points=n_sampling_points)
tangent_vec = curves_2d.to_tangent(
            5.0 * gs.random.rand(*(n_samples, n_sampling_points, dim)), base_curve
        )
metric_curves_2d.exp(
            tangent_vec,
            base_curve ,
        )
```

gives:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/GoogleDrive/My Drive/code/geomstats/geomstats/geometry/discrete_curves.py", line 716, in exp
    d_srv_tangent_vec = self.aux_differential_srv_transform(
  File "/Volumes/GoogleDrive/My Drive/code/geomstats/geomstats/geometry/discrete_curves.py", line 580, in aux_differential_srv_transform
    inner_prod = self.l2_metric.pointwise_inner_products(
  File "/Volumes/GoogleDrive/My Drive/code/geomstats/geomstats/geometry/discrete_curves.py", line 278, in pointwise_inner_products
    return gs.vectorize(
  File "/Volumes/GoogleDrive/My Drive/code/geomstats/geomstats/_backend/tensorflow/__init__.py", line 543, in vectorize
    return _tf.map_fn(lambda y: pyfunc(*y), elems=x, dtype=dtype)
  File "/Users/ninamiolane/opt/anaconda3/envs/geomstats38/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 617, in new_func
    return func(*args, **kwargs)
  File "/Users/ninamiolane/opt/anaconda3/envs/geomstats38/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 549, in new_func
    return func(*args, **kwargs)
  File "/Users/ninamiolane/opt/anaconda3/envs/geomstats38/lib/python3.8/site-packages/tensorflow/python/ops/map_fn.py", line 643, in map_fn_v2
    return map_fn(
  File "/Users/ninamiolane/opt/anaconda3/envs/geomstats38/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 549, in new_func
    return func(*args, **kwargs)
  File "/Users/ninamiolane/opt/anaconda3/envs/geomstats38/lib/python3.8/site-packages/tensorflow/python/ops/map_fn.py", line 440, in map_fn
    n_static.assert_is_compatible_with(
  File "/Users/ninamiolane/opt/anaconda3/envs/geomstats38/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py", line 288, in assert_is_compatible_with
    raise ValueError("Dimensions %s and %s are not compatible" %
ValueError: Dimensions 10 and 1 are not compatible
```

**Comment by luisfpereira** [comment]
`tenserflow` has been removed (#1778).
