### ISSUE TITLE
Bug: ValueError: buffer source array is read-only

### ISSUE THREAD

**Issue by Davidcohen2** [geomstats/geomstats#1637]
### Describe the bug

Scipy version 1.9.1 raised the following error: "ValueError: buffer source array is read-only."
Scipy version 1.8.1 works well.

### Steps/Code to Reproduce

Reproducing code:
from geomstats.geometry.spd_matrices import SPDMatrices
spd = SPDMatrices(100)
a=spd.random_point()

### Expected Behaviour

No error is thrown

### Actual Behaviour

Traceback (most recent call last):

  File "C:\Users\david\AppData\Local\Temp\ipykernel_18968\2594329883.py", line 3, in <cell line: 3>
    a=spd.random_point()

  File "C:\Users\david\anaconda3\envs\pt4\lib\site-packages\geomstats\geometry\spd_matrices.py", line 101, in random_point
    spd_mat = GeneralLinear.exp(Matrices.to_symmetric(mat))

  File "C:\Users\david\anaconda3\envs\pt4\lib\site-packages\geomstats\geometry\lie_group.py", line 226, in exp
    return expm(tangent_vec)

  File "C:\Users\david\anaconda3\envs\pt4\lib\site-packages\geomstats\_backend\numpy\linalg.py", line 28, in expm
    return np.vectorize(scipy.linalg.expm, signature="(n,m)->(n,m)")(x)

  File "C:\Users\david\anaconda3\envs\pt4\lib\site-packages\numpy\lib\function_base.py", line 2328, in __call__
    return self._vectorize_call(func=func, args=vargs)

  File "C:\Users\david\anaconda3\envs\pt4\lib\site-packages\numpy\lib\function_base.py", line 2402, in _vectorize_call
    res = self._vectorize_call_with_signature(func, args)

  File "C:\Users\david\anaconda3\envs\pt4\lib\site-packages\numpy\lib\function_base.py", line 2442, in _vectorize_call_with_signature
    results = func(*(arg[index] for arg in args))

  File "C:\Users\david\anaconda3\envs\pt4\lib\site-packages\scipy\linalg\_matfuncs.py", line 335, in expm
    lu = bandwidth(aw)

  File "_cythonized_array_utils.pyx", line 104, in scipy.linalg._cythonized_array_utils.bandwidth

  File "_cythonized_array_utils.pyx", line 114, in scipy.linalg._cythonized_array_utils.bandwidth_c

  File "stringsource", line 660, in View.MemoryView.memoryview_cwrapper

  File "stringsource", line 350, in View.MemoryView.memoryview.__cinit__

ValueError: buffer source array is read-only

### Your environment

```shell
The environment is created using the following code line:

conda create -n pt4 python pytorch torchvision torchaudio cudatoolkit=11.6 geomstats pandas spyder -c pytorch -c conda-forge

**Comment by lpereira95** [comment]
Thanks @Davidcohen2. I'll look to it soon.

(Related with #1620.)

**Comment by psarahdactyl** [comment]
Hi @lpereira95 I am getting this error too with both the code above and this code:
```
SO3 = SpecialOrthogonal(n=3)

rot1 = SO3.random_point()
rot2 = SO3.random_point()

print('version: ',np.__version__)
print(rot1,rot2)

times = np.array([0, 0.5, 1])
interp_rots = SO3.bi_invariant_metric.geodesic(initial_point=rot1,end_point=rot2)
interp_rots(times)
```
It's strange because I'm running this code within the animation software blender. These errors only happen within blender, not the regular python terminal even though all versions are the same between each. The versions are: 
```
>>> import numpy as np
>>> np.__version__
'1.23.4'
>>> import scipy as sp
>>> sp.__version__
'1.9.2'
>>> import geomstats as gs
>>> gs.__version__
'2.5.0'
```
and I'm using the numpy backend for geomstats 

my errors are:
```
Error: Python: Traceback (most recent call last):
  File "/Users/sak/Documents/Documents-sarahs-macbook/blends/punch-frame-rate-tests-real-positions 186.blend/track_bones.py", line 137, in <module>
  File "/Users/sak/Documents/Documents-sarahs-macbook/blends/punch-frame-rate-tests-real-positions 186.blend/track_bones.py", line 133, in test_interp
  File "/Applications/Blender3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/geomstats/geometry/connection.py", line 619, in path
    points_at_time_t = [
  File "/Applications/Blender3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/geomstats/geometry/connection.py", line 620, in <listcomp>
    self.exp(tv, pt) for tv, pt in zip(tangent_vecs, initial_point)
  File "/Applications/Blender3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/geomstats/geometry/invariant_metric.py", line 1240, in exp
    return self.group.exp(tangent_vec, base_point)
  File "/Applications/Blender3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/geomstats/geometry/lie_group.py", line 228, in exp
    return cls.compose(base_point, cls.exp(lie_algebra_vec))
  File "/Applications/Blender3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/geomstats/geometry/lie_group.py", line 226, in exp
    return expm(tangent_vec)
  File "/Applications/Blender3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/geomstats/_backend/numpy/linalg.py", line 28, in expm
    return np.vectorize(scipy.linalg.expm, signature="(n,m)->(n,m)")(x)
  File "/Applications/Blender3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/numpy/lib/function_base.py", line 2328, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/Applications/Blender3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/numpy/lib/function_base.py", line 2402, in _vectorize_call
    res = self._vectorize_call_with_signature(func, args)
  File "/Applications/Blender3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/numpy/lib/function_base.py", line 2442, in _vectorize_call_with_signature
    results = func(*(arg[index] for arg in args))
  File "/Applications/Blender3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/scipy/linalg/_matfuncs.py", line 335, in expm
    lu = bandwidth(aw)
  File "_cythonized_array_utils.pyx", line 104, in scipy.linalg._cythonized_array_utils.bandwidth
  File "_cythonized_array_utils.pyx", line 114, in scipy.linalg._cythonized_array_utils.bandwidth_c
  File "stringsource", line 660, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 350, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

**Comment by lpereira95** [comment]
Thanks for reporting this @psarahdactyl. Very nice to know you are trying to use geomstats within blender.

I think the problem is related with blender's python version (3.10). I guess in your terminal you should be using python 3.8/3.9. I'll investigate this and I'll come to you soon.

Just a question: are you installing geomstats from PyPI or from github? I advise the github installation.

**Comment by psarahdactyl** [comment]
@lpereira95 I've been installing (and upgrading versions) from pip. I can try the github way and get back to you. installing a python package within blender's python is a bit annoying. I had to write a script that uses the python subprocess module. I can share that script if it's useful, but first I'll try the github installation

**Comment by psarahdactyl** [comment]
so when I try to install via github, I can successfully clone and "install" the package:
```
| /Applications/Blender3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/geomstats @ ResNet-39-218 (sak)
| 💯 => pip3 install .
Processing /Applications/Blender3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/geomstats
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Requirement already satisfied: joblib>=0.14.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geomstats==2.5.0) (1.2.0)
Requirement already satisfied: matplotlib>=3.3.4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geomstats==2.5.0) (3.6.1)
Requirement already satisfied: numpy>=1.18.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geomstats==2.5.0) (1.23.4)
Requirement already satisfied: pandas>=1.1.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geomstats==2.5.0) (1.5.1)
Requirement already satisfied: scikit-learn>=0.22.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geomstats==2.5.0) (1.1.2)
Requirement already satisfied: scipy>=1.9 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geomstats==2.5.0) (1.9.2)
Requirement already satisfied: pyparsing>=2.2.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (21.3)
Requirement already satisfied: pillow>=6.2.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (9.2.0)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (4.37.4)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (0.11.0)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (1.0.5)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas>=1.1.5->geomstats==2.5.0) (2022.5)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.4->geomstats==2.5.0) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-learn>=0.22.1->geomstats==2.5.0) (3.1.0)
Using legacy 'setup.py install' for geomstats, since package 'wheel' is not installed.
Installing collected packages: geomstats
  Attempting uninstall: geomstats
    Found existing installation: geomstats 2.5.0
    Uninstalling geomstats-2.5.0:
      Successfully uninstalled geomstats-2.5.0
    Running setup.py install for geomstats ... done
Successfully installed geomstats-2.5.0
```

but when I try to import from geometry, it can't find the submodule:
```
from geomstats.geometry.special_orthogonal import SpecialOrthogonal
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
ModuleNotFoundError: No module named 'geomstats.geometry'
```

**Comment by lpereira95** [comment]
@psarahdactyl  can you try [this](https://stackoverflow.com/questions/61678445/could-not-build-wheels-since-package-wheel-is-not-installed)? Not sure it will help, but it looks like `pip` is falling back to a legacy way of installing " since package 'wheel' is not installed."

**Comment by psarahdactyl** [comment]
@lpereira95 
I installed wheel and now when I install I see this:
```
| 💯 => pip3 install .
Processing /Applications/Blender3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/geomstats
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Requirement already satisfied: joblib>=0.14.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geomstats==2.5.0) (1.2.0)
Requirement already satisfied: matplotlib>=3.3.4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geomstats==2.5.0) (3.6.1)
Requirement already satisfied: numpy>=1.18.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geomstats==2.5.0) (1.23.4)
Requirement already satisfied: pandas>=1.1.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geomstats==2.5.0) (1.5.1)
Requirement already satisfied: scikit-learn>=0.22.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geomstats==2.5.0) (1.1.2)
Requirement already satisfied: scipy>=1.9 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geomstats==2.5.0) (1.9.2)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (4.37.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (9.2.0)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (0.11.0)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (21.3)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats==2.5.0) (1.0.5)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas>=1.1.5->geomstats==2.5.0) (2022.5)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.4->geomstats==2.5.0) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-learn>=0.22.1->geomstats==2.5.0) (3.1.0)
Building wheels for collected packages: geomstats
  Building wheel for geomstats (setup.py) ... done
  Created wheel for geomstats: filename=geomstats-2.5.0-py3-none-any.whl size=7617750 sha256=dac93ce2b12b1bded763504b00c85fc2f6adaf7e54020ec5dc3c94b48e9553a6
  Stored in directory: /private/var/folders/1h/ygmxfx2933lg3n47qtxn__440000gp/T/pip-ephem-wheel-cache-jhbprtpt/wheels/19/3e/4d/ed40c5c132e7613c13a58e20c9f91dabc2e078eeba47dc631a
Successfully built geomstats
Installing collected packages: geomstats
  Attempting uninstall: geomstats
    Found existing installation: geomstats 2.5.0
    Uninstalling geomstats-2.5.0:
      Successfully uninstalled geomstats-2.5.0
Successfully installed geomstats-2.5.0
```

for some reason when I install through github, I can't import submodules. for example:
```
>>> from geomstats.geometry.special_euclidean import SpecialEuclidean
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
ModuleNotFoundError: No module named 'geomstats.geometry'
```
but `import geomstats` by itself seems to work?

this is only within blender. it works in the python terminal. 
this problem doesn't happen when I install through pip.
the only difference I can see between a pip install and a github install is that pip gives a `dist-info` directory, but I don't fully understand what that directory is and why that would have an effect like this.

**Comment by psarahdactyl** [comment]
when I install through pip through blender I see this:
```
Collecting geomstats
  Using cached geomstats-2.5.0-py3-none-any.whl (7.5 MB)
Requirement already satisfied: joblib>=0.14.1 in ./.local/lib/python3.10/site-packages (from geomstats) (1.2.0)
Requirement already satisfied: matplotlib>=3.3.4 in ./.local/lib/python3.10/site-packages (from geomstats) (3.6.1)
Requirement already satisfied: pandas>=1.1.5 in ./.local/lib/python3.10/site-packages (from geomstats) (1.5.0)
Requirement already satisfied: scikit-learn>=0.22.1 in ./.local/lib/python3.10/site-packages (from geomstats) (1.1.2)
Requirement already satisfied: scipy>=1.4.1 in ./.local/lib/python3.10/site-packages (from geomstats) (1.9.2)
Requirement already satisfied: numpy>=1.18.1 in /Applications/Blender3.3.app/Contents/Resources/3.3/python/lib/python3.10/site-packages (from geomstats) (1.23.4)
Requirement already satisfied: pyparsing>=2.2.1 in ./.local/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats) (3.0.9)
Requirement already satisfied: packaging>=20.0 in ./.local/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats) (21.3)
Requirement already satisfied: cycler>=0.10 in ./.local/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./.local/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats) (4.37.4)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.local/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in ./.local/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats) (1.0.5)
Requirement already satisfied: pillow>=6.2.0 in ./.local/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats) (9.2.0)
Requirement already satisfied: python-dateutil>=2.7 in ./.local/lib/python3.10/site-packages (from matplotlib>=3.3.4->geomstats) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./.local/lib/python3.10/site-packages (from pandas>=1.1.5->geomstats) (2022.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.local/lib/python3.10/site-packages (from scikit-learn>=0.22.1->geomstats) (3.1.0)
Requirement already satisfied: six>=1.5 in ./.local/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.4->geomstats) (1.16.0)
Installing collected packages: geomstats
Successfully installed geomstats-2.5.0
```
and then I am back to the original problem. I can import `geomstats.geometry` but I see the `ValueError: buffer source array is read-only`

**Comment by psarahdactyl** [comment]
@lpereira95 it worked!! doing `pip install git+https://github.com/geomstats/geomstats.git@master#egg=geomstats` from blender worked :)

**Comment by psarahdactyl** [comment]
@luisfpereira I have bad news. when I install geomstats through pip or conda, with python 3.9 or 3.10, with numpy or autograd backend. I still get the error. I only _don't_ get it when I install through github. none of the code is in blender this time.

here is my code:
```
import numpy as np
import os

os.environ["GEOMSTATS_BACKEND"] = "autograd"
from geomstats.geometry.special_orthogonal import SpecialOrthogonal

SO3 = SpecialOrthogonal(n=3)

rot1 = SO3.random_point()
rot2 = SO3.random_point()

print(rot1, rot2)
print(rot1.shape, rot2.shape)

times = np.array([0.0, 0.5, 1])

interp_rots = SO3.bi_invariant_metric.geodesic(initial_point=rot1,end_point=rot2)

# this is where the error happens:
new_rots = interp_rots(times)
```

and here is the error:
```
| 💯 => python test-geomstats.py
INFO: Using autograd backend
[[-0.48353147 -0.86177076 -0.15345512]
 [ 0.08090694 -0.21856219  0.97246318]
 [-0.87157982  0.45780097  0.17540493]] [[-0.66811748 -0.74075589  0.06999813]
 [ 0.21564564 -0.1027394   0.97105179]
 [-0.71212077  0.66387146  0.22838277]]
(3, 3) (3, 3)
Traceback (most recent call last):
  File "/Users/sak/Documents/test-geomstats.py", line 20, in <module>
    new_rots = interp_rots(times)
  File "/Users/sak/opt/anaconda3/lib/python3.9/site-packages/geomstats/geometry/connection.py", line 619, in path
    points_at_time_t = [
  File "/Users/sak/opt/anaconda3/lib/python3.9/site-packages/geomstats/geometry/connection.py", line 620, in <listcomp>
    self.exp(tv, pt) for tv, pt in zip(tangent_vecs, initial_point)
  File "/Users/sak/opt/anaconda3/lib/python3.9/site-packages/geomstats/geometry/invariant_metric.py", line 1240, in exp
    return self.group.exp(tangent_vec, base_point)
  File "/Users/sak/opt/anaconda3/lib/python3.9/site-packages/geomstats/geometry/lie_group.py", line 228, in exp
    return cls.compose(base_point, cls.exp(lie_algebra_vec))
  File "/Users/sak/opt/anaconda3/lib/python3.9/site-packages/geomstats/geometry/lie_group.py", line 226, in exp
    return expm(tangent_vec)
  File "/Users/sak/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "/Users/sak/opt/anaconda3/lib/python3.9/site-packages/geomstats/_backend/autograd/linalg.py", line 33, in expm
    return np.vectorize(asp.expm, signature="(n,m)->(n,m)")(x)
  File "/Users/sak/opt/anaconda3/lib/python3.9/site-packages/numpy/lib/function_base.py", line 2163, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/Users/sak/opt/anaconda3/lib/python3.9/site-packages/numpy/lib/function_base.py", line 2237, in _vectorize_call
    res = self._vectorize_call_with_signature(func, args)
  File "/Users/sak/opt/anaconda3/lib/python3.9/site-packages/numpy/lib/function_base.py", line 2277, in _vectorize_call_with_signature
    results = func(*(arg[index] for arg in args))
  File "/Users/sak/opt/anaconda3/lib/python3.9/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "/Users/sak/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_matfuncs.py", line 335, in expm
    lu = bandwidth(aw)
  File "_cythonized_array_utils.pyx", line 104, in scipy.linalg._cythonized_array_utils.bandwidth
  File "_cythonized_array_utils.pyx", line 114, in scipy.linalg._cythonized_array_utils.bandwidth_c
  File "stringsource", line 660, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 350, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

I also tried installing the way you suggested above in my conda environment like this (before that I had it as `geomstats>=2.5.0` and it didn't work that way either):
```
 name: supersampling
 channels:
   - defaults
 dependencies:
   - python=3.10
   - pip
   - matplotlib>=3.5.1
   - pip:
     - autograd>=1.3
     - hyperopt==0.2.5
     - jupyter
     - jupyterlab-code-formatter
     - "git+https://github.com/geomstats/geomstats.git@master#egg=geomstats"
     - numpy>=1.23.0
     - quaternionic
     - ray
     - ray[tune]
     - wandb
     - -r dev-requirements.txt
```
