### ISSUE TITLE
Bug: master fails during pytest collection for spd_matrices

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#1669]
### Describe the bug

On the most recent master branch, running `pytest tests/tests_geomstats/test_spd_matrices.py` in autograd backend fails during pytest collection:

<img width="1121" alt="Screen Shot 2022-10-06 at 11 16 55 AM" src="https://user-images.githubusercontent.com/8267869/194275215-78340355-8871-4212-81c8-4e7e2ee6282f.png">

This comes from a bug in the `random_point` method of the `SPDMatrices` class.

It seems that this was not caught by our CI during merging of the most recent PRs:
https://github.com/geomstats/geomstats/actions/workflows/test.yml

We should try and understand why this is. Could our CI not be testing all files upon merging to master?

### Steps/Code to Reproduce

```
from geomstats.geometry.spd_matrices import SPDMatrices
spd = SPDMatrices(n=2)
spd.random_point(n_samples=10).shape
```
Gives:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/GoogleDrive/My Drive/code/geomstats/geomstats/geometry/spd_matrices.py", line 101, in random_point
    spd_mat = GeneralLinear.exp(Matrices.to_symmetric(mat))
  File "/Volumes/GoogleDrive/My Drive/code/geomstats/geomstats/geometry/lie_group.py", line 226, in exp
    return expm(tangent_vec)
  File "/Users/ninamiolane/opt/anaconda3/envs/geomstats38/lib/python3.8/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "/Users/ninamiolane/opt/anaconda3/envs/geomstats38/lib/python3.8/site-packages/scipy/linalg/matfuncs.py", line 255, in expm
    return scipy.sparse.linalg.expm(A)
  File "/Users/ninamiolane/opt/anaconda3/envs/geomstats38/lib/python3.8/site-packages/scipy/sparse/linalg/matfuncs.py", line 591, in expm
    return _expm(A, use_exact_onenorm='auto')
  File "/Users/ninamiolane/opt/anaconda3/envs/geomstats38/lib/python3.8/site-packages/scipy/sparse/linalg/matfuncs.py", line 602, in _expm
    raise ValueError('expected a square matrix')
ValueError: expected a square matrix
```

### Expected Behaviour

(10, 2, 2)

### Actual Behaviour

Error thrown.

### Your environment

```shell
Python 3.8.10
Geomstats master
```

**Comment by ninamiolane** [comment]
Awesome, thanks! It fixed it indeed.
