### ISSUE TITLE
Bug: Vectorizaton of log map for PullbackMetric

### ISSUE THREAD

**Issue by TheoBertrand-Dauphine** [geomstats/geomstats#1838]
### Describe the bug

There seems to be an issue with the vectorization of the exp map in connection.py as when it is called by the function metric.log with multiple "target" points. 

### Steps/Code to Reproduce

```
def immersion(coords):
    x = coords[..., 0]
    y = coords[..., 1]
    return gs.array(
        [x, y]
    )
metric = PullbackMetric(dim=2, embedding_dim=2, immersion=immersion)

N=20
X = immersion(torch.tensor(torch.randn([N,2])))

a = metric.log(point = X.T, base_point=X[0])

print(a)
```

### Expected Behaviour

No error

### Actual Behaviour

INFO: Using pytorch backend
/home/tbertrand/Bureau/brownian_bridge_geod.py:94: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = immersion(torch.tensor(torch.randn([N,2])))
Traceback (most recent call last):
  File "/home/tbertrand/Bureau/brownian_bridge_geod.py", line 97, in <module>
    a = metric.log(point = X.T, base_point=X[0])
  File "/home/tbertrand/anaconda3/envs/env_stochastic/lib/python3.10/site-packages/geomstats/geometry/connection.py", line 188, in log
    res = minimize(
  File "/home/tbertrand/anaconda3/envs/env_stochastic/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 699, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/home/tbertrand/anaconda3/envs/env_stochastic/lib/python3.10/site-packages/scipy/optimize/_lbfgsb_py.py", line 306, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "/home/tbertrand/anaconda3/envs/env_stochastic/lib/python3.10/site-packages/scipy/optimize/_optimize.py", line 263, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/tbertrand/anaconda3/envs/env_stochastic/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 158, in __init__
    self._update_fun()
  File "/home/tbertrand/anaconda3/envs/env_stochastic/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "/home/tbertrand/anaconda3/envs/env_stochastic/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/tbertrand/anaconda3/envs/env_stochastic/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in fun_wrapped
    fx = fun(np.copy(x), *args)
  File "/home/tbertrand/anaconda3/envs/env_stochastic/lib/python3.10/site-packages/scipy/optimize/_optimize.py", line 76, in __call__
    self._compute_if_needed(x, *args)
  File "/home/tbertrand/anaconda3/envs/env_stochastic/lib/python3.10/site-packages/scipy/optimize/_optimize.py", line 70, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/tbertrand/anaconda3/envs/env_stochastic/lib/python3.10/site-packages/geomstats/_backend/pytorch/autodiff.py", line 148, in func_with_grad
    value = func(*args, **kwargs)
  File "/home/tbertrand/anaconda3/envs/env_stochastic/lib/python3.10/site-packages/geomstats/geometry/connection.py", line 181, in objective
    delta = self.exp(velocity, base_point, n_steps, step) - point
  File "/home/tbertrand/anaconda3/envs/env_stochastic/lib/python3.10/site-packages/geomstats/geometry/connection.py", line 128, in exp
    initial_state = gs.stack([base_point, tangent_vec])
RuntimeError: stack expects each tensor to be equal size, but got [20] at entry 0 and [20, 2] at entry 1

### Your environment

```shell
geomstats version 2.5.0
```

**Comment by luisfpereira** [comment]
This is now fixed. We've updated `PullbackMetric`. You need to make the following changes to accomplish the same goal:

```python
from geomstats.geometry.base import ImmersetSet

class MySpace(ImmersedSet):
    
    def __init__(self):
        super().__init__(dim=2)
        
    def _define_embedding_space(self):
        return Euclidean(dim=self.dim)
    
    def immersion(self, coords):
        x = coords[..., 0]
        y = coords[..., 1]
        
        return gs.stack([x, y], axis=-1)
```

instead of only 

```python
def immersion(coords):
    x = coords[..., 0]
    y = coords[..., 1]
    return gs.array(
        [x, y]
    )

```

and then

```python
space = MySpace()
space.equip_with_metric(PullbackMetric)
```

Notice you'll be unable to compute log because the jacobian is independent of the input:

```RuntimeError: While computing the hessian, found that the jacobian of the user-provided function with respect to input 0 is independent of the input.```

The bug related with vectorization is solved though.

Notice also the change I've made in `immersion` wrt to the output -> its shapes need to be `[..., 2]` instead of `[2, ...]` as before.

Let me know if I can help further.
