### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by MAeolus** [geomstats/geomstats#904]
Hello, I encountered an error when I trying to train a CNN with geodesic distance loss on SE3.
There is a short code which could reproduce it.
It seems like some tensor was modified by an **inplace operation** but I couldn't find which tensor and where the inplace opreation is.
Am I use the geodesic loss in the wrong way?
**torch==1.4.0
geomstats==2.2.0**

```import torch
import torch.nn as nn
from geomstats.geometry.special_euclidean import SpecialEuclidean
import utils
LR = 0.005

autoencoder = nn.Linear(28 * 28, 6)
optimizer = torch.optim.Adam(autoencoder.parameters(), lr=LR)
SE3 = SpecialEuclidean(n=3, point_type='vector')
metric = SE3.left_canonical_metric
criterion = utils.Geodesic_loss(group=SE3, metric=SE3.left_canonical_metric)
with torch.autograd.set_detect_anomaly(True):
    x = torch.randn(1, 28*28)
    encoded = autoencoder(x)
    gt = torch.rand_like(encoded, dtype=torch.float32)
    loss_val = torch.mean(criterion.loss(gt, encoded))
    loss_val.backward()
```

**the geodesic loss:**
```
class Geodesic_loss:
    def __init__(self, group, metric):
        self.group = group  # SE3 = SpecialEuclidean(n=3, point_type='vector')
        self.metric = metric  # metric = SE3.left_canonical_metric
    def loss(self, y_pred, y_true):
        """Loss function given by a Riemannian metric on a Lie group.

        Parameters
        ----------
        y_pred : array-like
            Prediction on SE(3).
        y_true : array-like
            Ground-truth on SE(3).
        metric : RiemannianMetric
            Metric used to compute the loss and gradient.
        representation : str, {'vector', 'matrix'}
            Representation chosen for points in SE(3).

        Returns
        -------
        lie_loss : array-like
            Loss using the Riemannian metric.
        """
        if gs.ndim(y_pred) == 1:
            y_pred = gs.expand_dims(y_pred, axis=0)
        if gs.ndim(y_true) == 1:
            y_true = gs.expand_dims(y_true, axis=0)

        lie_loss = lie_group.loss(y_pred, y_true, self.group, self.metric)
        if gs.ndim(lie_loss) == 2:
            lie_loss = gs.squeeze(lie_loss, axis=1)
        if gs.ndim(lie_loss) == 1 and gs.shape(lie_loss)[0] == 1:
            lie_loss = gs.squeeze(lie_loss, axis=0)

        return lie_loss
```

**the error:**
```
INFO: Using pytorch backend
Warning: Traceback of forward call that caused the error:
  File "/public/admin/projects/model/test_2.py", line 19, in <module>
    loss_val = torch.mean(criterion.loss(gt, encoded))
  File "//public/admin/projects/model/utils.py", line 113, in loss
    lie_loss = lie_group.loss(y_pred, y_true, self.group, self.metric)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/geomstats/geometry/lie_group.py", line 37, in loss
    metric_loss = riemannian_metric.loss(y_pred, y_true, metric)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/geomstats/geometry/riemannian_metric.py", line 38, in loss
    sq_dist = metric.squared_dist(y_pred, y_true)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/geomstats/geometry/riemannian_metric.py", line 270, in squared_dist
    log = self.log(point=point_b, base_point=point_a)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/geomstats/geometry/invariant_metric.py", line 359, in log
    log_from_id = self.log_from_identity(point_near_id)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/geomstats/geometry/invariant_metric.py", line 314, in log_from_identity
    log = self.left_log_from_identity(point)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/geomstats/geometry/invariant_metric.py", line 295, in left_log_from_identity
    tangent_vec=log, metric=self)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/geomstats/vectorization.py", line 104, in wrapper
    result = function(*vect_args, **vect_kwargs)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/geomstats/geometry/special_euclidean.py", line 274, in regularize_tangent_vec_at_identity
    tangent_vec, self.identity, metric)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/geomstats/geometry/special_euclidean.py", line 685, in regularize_tangent_vec
    metric=rot_metric)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/geomstats/vectorization.py", line 104, in wrapper
    result = function(*vect_args, **vect_kwargs)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/geomstats/geometry/special_orthogonal.py", line 764, in regularize_tangent_vec
    tangent_vec_at_id, metric)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/geomstats/vectorization.py", line 104, in wrapper
    result = function(*vect_args, **vect_kwargs)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/geomstats/geometry/special_orthogonal.py", line 693, in regularize_tangent_vec_at_identity
    tangent_vec_canonical_norm = gs.linalg.norm(tangent_vec, axis=-1)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/geomstats/_backend/pytorch/linalg.py", line 56, in norm
    return torch.norm(x, p=ord, dim=axis)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/torch/functional.py", line 769, in norm
    return torch._C._VariableFunctions.norm(input, p, dim, keepdim=keepdim)
 (print_stack at /pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:57)
Traceback (most recent call last):
  File "/public/admin/python_projects/poseEsti/model/inplacetest_2.py", line 22, in <module>
    loss_val.backward()
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/public/admin/envs/pytorch/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1]], which is output 0 of NormBackward1, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

**Comment by nguigs** [comment]
Hi @MAeolus, thank you for your detailed report and sorry for the very late response! 

The vector representation of SE3 does use many inplace operations and this is something that will be fixed in the coming weeks to allow gradient computations. Unfortunately the matrix representation cannot be used with pytorch because the matrix logarithm and its gradient are not implemented in pytorch ([see open issue](https://github.com/pytorch/pytorch/issues/9983#issue-345497745)).

**Comment by nguigs** [comment]
So I found the methods that used inplace operations (`regularize`, `set_diag`) and rewrote them in #914. The following code now runs for me:
```python
import os
import torch
import torch.nn as nn

os.environ['GEOMSTATS_BACKEND'] = 'pytorch'
import geomstats.geometry.lie_group as lie_group
from geomstats.geometry.special_euclidean import SpecialEuclidean
LR = 0.005


class GeodesicLoss:
    def __init__(self, group, metric):
        self.group = group  # SE3 = SpecialEuclidean(n=3, point_type='vector')
        self.metric = metric  # metric = SE3.left_canonical_metric
    def loss(self, y_pred, y_true):
        """Loss function given by a Riemannian metric on a Lie group.

        Parameters
        ----------
        y_pred : array-like
            Prediction on SE(3).
        y_true : array-like
            Ground-truth on SE(3).
        metric : RiemannianMetric
            Metric used to compute the loss and gradient.
        representation : str, {'vector', 'matrix'}
            Representation chosen for points in SE(3).

        Returns
        -------
        lie_loss : array-like
            Loss using the Riemannian metric.
        """
        lie_loss = lie_group.loss(
            y_pred, y_true, self.group, self.metric)
        return lie_loss

autoencoder = nn.Linear(28 * 28, 6)
optimizer = torch.optim.Adam(autoencoder.parameters(), lr=LR)
SE3 = SpecialEuclidean(n=3, point_type='vector')
metric = SE3.left_canonical_metric
criterion = GeodesicLoss(group=SE3, metric=SE3.left_canonical_metric)
with torch.autograd.set_detect_anomaly(True):
    x = torch.randn(1, 28*28)
    encoded = autoencoder(x)
    gt = torch.rand_like(encoded, dtype=torch.float32)
    loss_val = torch.mean(criterion.loss(gt, encoded))
    loss_val.backward()
```
Let me know if this works for you once its merged.

**Comment by MAeolus** [comment]
@nguigs 

It works. Thank you so much.
